import { expect, test } from '@playwright/test'
async function ready(page: import('@playwright/test').Page) {
 await page.waitForFunction(()=>{const app=(document.querySelector('#__nuxt') as any)?.__vue_app__?.config.globalProperties.$nuxt;return app&&!app.isHydrating})
}
test('all five reference pages retain real interactions',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 await page.goto('/'); await ready(page)
 await expect(page.locator('.suite-today')).toBeVisible()
 await expect(page.locator('.suite-metrics article')).toHaveCount(3)
 if(info.project.name==='desktop') await page.setViewportSize({width:1600,height:1000})
 await page.screenshot({path:`artifacts/suite-today-${info.project.name}.png`})
 await page.goto('/calendar'); await ready(page)
 await expect(page.locator('.suite-day-column')).toHaveCount(7)
 const initial=await page.locator('.suite-calendar-toolbar strong').innerText()
 await page.getByRole('button',{name:'下一周',exact:true}).click()
 await expect(page.locator('.suite-calendar-toolbar strong')).not.toHaveText(initial)
 await page.getByRole('button',{name:'今天',exact:true}).click()
 await page.getByRole('button',{name:'新建任务',exact:true}).first().click()
 const editor=page.locator('.suite-inline-editor')
 await editor.locator('input[name="title"]').fill('周历布局验收记录')
 await expect(editor.locator('input[name="dueTime"]')).toHaveCount(0)
 await expect(editor.locator('input[name="startDate"]')).toBeVisible()
 await editor.getByRole('button',{name:'创建任务',exact:true}).click()
 await expect(page.locator('.suite-calendar-event').filter({hasText:'周历布局验收记录'})).toHaveCount(1)
 await page.locator('.suite-calendar-event').filter({hasText:'周历布局验收记录'}).click()
 await expect(editor.locator('input[name="title"]')).toHaveValue('周历布局验收记录')
  await page.screenshot({path:`artifacts/suite-calendar-${info.project.name}.png`})
 await page.goto('/inbox'); await ready(page)
 await page.getByLabel('快速记录收集箱').fill('收集箱选择验收')
 await page.getByRole('button',{name:'保存记录',exact:true}).click()
 await page.getByLabel('选择 收集箱选择验收',{exact:true}).check()
 await expect(page.locator('.suite-ai')).toContainText('已选择 1 条记录')
 await page.screenshot({path:`artifacts/suite-inbox-${info.project.name}.png`})
 await page.goto('/project?project=10000000-0000-4000-8000-000000000002'); await ready(page)
 await expect(page.locator('.suite-tabs button')).toHaveCount(5)
 await expect(page.locator('.suite-kanban')).toBeVisible()
 await page.screenshot({path:`artifacts/suite-project-${info.project.name}.png`})
 await page.locator('.suite-tabs').getByRole('button',{name:'文件',exact:true}).click()
 await expect(page.getByRole('button',{name:'添加带附件的任务',exact:true})).toBeVisible()
 await page.goto('/settings'); await ready(page)
 await expect(page.locator('.suite-inline-models')).toBeVisible()
 await page.screenshot({path:`artifacts/suite-settings-${info.project.name}.png`})
 await page.locator('.suite-settings-nav').getByRole('link',{name:'软件更新',exact:true}).click()
 await expect(page.locator('.suite-inline-info [data-update-card]')).toBeVisible()
 await page.locator('.suite-settings-nav').getByRole('link',{name:'数据与备份',exact:true}).click()
 await expect(page.getByRole('button',{name:'导出工作区备份',exact:true})).toBeVisible()
 expect(errors).toEqual([])
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
})
