<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { deriveProjectProgress } from '#shared/workspace'
import SuiteHeader from '../components/suite/SuiteHeader.vue'
import ProjectProgressPanel from '../components/projects/ProjectProgressPanel.vue'
const workspace=useWorkspace(); const ui=useWorkspaceUi(); const route=useRoute()
const tab=ref('overview')
const project=computed(()=>workspace.projects.value.find(p=>p.id===route.query.project)??null)
const tasks=computed(()=>workspace.tasks.value.filter(t=>t.projectId===project.value?.id))
const milestones=computed(()=>workspace.milestones.value.filter(m=>m.projectId===project.value?.id))
const progress=computed(()=>project.value?deriveProjectProgress(project.value,milestones.value,tasks.value):0)
const files=computed(()=>tasks.value.flatMap(task=>task.attachments.map(file=>({file,task}))))
const columns=[{id:'todo',label:'待办'},{id:'in_progress',label:'进行中'},{id:'done',label:'已完成'}]
function columnTasks(id:string) { return tasks.value.filter(t=>id==='todo'?['inbox','todo','waiting'].includes(t.status):t.status===id) }
onMounted(()=>{if(!workspace.ready.value) void workspace.load()})
</script>
<template><main class="suite-page"><SuiteHeader :section="`项目 / ${project?.name??'项目'}`" /><div class="suite-content">
<template v-if="project"><header class="suite-heading"><div><h1><span class="suite-project-icon" :style="{color:project.color}"><UIcon name="i-lucide-folder" /></span>{{ project.name }}</h1><p>{{ project.description || '从创意到成果，每一步都清晰可见。' }}</p></div><button class="suite-secondary" @click="ui.openFeishuLinks"><UIcon name="i-lucide-external-link" />打开飞书</button><button class="suite-icon" aria-label="编辑项目" @click="ui.openEditProject(project.id)"><UIcon name="i-lucide-ellipsis" /></button></header>
<nav class="suite-tabs" aria-label="项目页签"><button v-for="item in [{id:'overview',label:'概览'},{id:'tasks',label:'任务'},{id:'milestones',label:'里程碑'},{id:'files',label:'文件'},{id:'settings',label:'设置'}]" :key="item.id" :class="{active:tab===item.id}" @click="tab=item.id">{{item.label}}</button></nav>
<section v-if="tab==='overview'" class="suite-project-overview"><article class="suite-card"><h2>项目进度</h2><div class="suite-progress-heading"><strong>{{progress}}%</strong><span class="focus-segment-progress"><i :style="{width:`${progress}%`}" /></span></div><div class="suite-milestone-track"><button v-for="m in milestones" :key="m.id" @click="ui.openEditMilestone(m.id)"><i :class="m.status" /><strong>{{m.title}}</strong><small>{{m.targetDate??'未设日期'}}</small><span>{{{planned:'待开始',in_progress:'进行中',blocked:'已阻塞',completed:'已完成'}[m.status]}}</span></button><button v-if="!milestones.length" @click="ui.openNewMilestone(project.id)">＋ 添加首个里程碑</button></div></article><article class="suite-card"><header><h2>项目信息</h2><button @click="ui.openEditProject(project.id)">编辑</button></header><dl class="suite-info"><dt>创建日期</dt><dd>{{project.createdAt.slice(0,10)}}</dd><dt>计划完成</dt><dd>{{project.targetDate??'未设置'}}</dd><dt>任务数量</dt><dd>{{tasks.length}} 项</dd><dt>当前状态</dt><dd>{{{planned:'计划中',active:'进行中',paused:'已暂停',completed:'已完成'}[project.status]}}</dd></dl><h3>项目简介</h3><p>{{project.description||'暂无简介，可点击编辑补充。'}}</p></article></section>
<section v-if="tab==='overview'||tab==='tasks'" class="suite-section"><header><h2>任务看板</h2><button @click="ui.openNewTask(project.id)">＋ 新建任务</button></header><div class="suite-kanban"><div v-for="column in columns" :key="column.id" :class="column.id"><header><span>{{column.label}} <b>{{columnTasks(column.id).length}}</b></span><button @click="ui.openNewTask(project.id)">＋</button></header><article v-for="task in columnTasks(column.id)" :key="task.id" class="suite-board-task"><button class="suite-check" :class="{checked:!!task.completedAt}" :aria-label="`完成 ${task.title}`" @click="workspace.setTaskCompleted(task.id,!task.completedAt)"><UIcon v-if="task.completedAt" name="i-lucide-check" /></button><button @click="ui.openEditTask(task.id)"><strong>{{task.title}}</strong><small>{{task.dueDate??'未设截止日期'}}</small></button><span v-if="task.priority" class="suite-priority" :class="task.priority??''">{{{high:'高',medium:'中',low:'低'}[task.priority??'low']}}</span></article><p v-if="!columnTasks(column.id).length" class="suite-empty">暂无任务</p></div></div></section>
<ProjectProgressPanel v-if="tab==='milestones'" :project="project" :milestones="workspace.milestones.value" :tasks="workspace.tasks.value" />
<section v-if="tab==='overview'||tab==='files'" class="suite-section"><header><h2>项目文件</h2><button @click="tab==='overview'?tab='files':ui.openNewTask(project.id)">{{tab==='overview'?'查看全部':'添加带附件的任务'}}</button></header><div class="suite-files"><button v-for="{file,task} in (tab==='overview'?files.slice(0,4):files)" :key="`${task.id}-${file.id}`" @click="ui.openEditTask(task.id)"><UIcon :name="file.mimeType.startsWith('image/')?'i-lucide-image':'i-lucide-file-text'" /><span><strong>{{file.name}}</strong><small>{{(file.size/1024).toFixed(1)}} KB · {{task.title}}</small></span></button></div><p v-if="!files.length" class="suite-empty">暂无附件。在项目任务中添加文件或图片后，会汇总到这里。</p></section>
<section v-if="tab==='settings'" class="suite-card"><h2>项目设置</h2><p>管理名称、简介、颜色、状态与截止日期。</p><button class="suite-primary" @click="ui.openEditProject(project.id)">编辑项目资料</button><hr><button class="suite-danger" @click="ui.askDeleteProject(project.id)">将项目移入回收站</button></section>
</template><section v-else class="suite-empty"><h1>选择一个项目</h1><p>从左侧打开项目，或创建新的项目。</p><button class="suite-primary" @click="ui.openNewProject">新建项目</button></section>
</div></main></template>
